### ISSUE TITLE
[RFE] add dark theme support

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#102]
There are some minor issues with dark themes, e.g.:
- #87 : custom colors for info bar ("status bar") are broken. Already fixed in #104 
- https://github.com/timlau/yumex-dnf/issues/74#issuecomment-157030580 : dark theme detection in yumex-dnf doesn't work the same way as in other Gtk+ applications
- https://github.com/timlau/yumex-dnf/issues/74#issuecomment-170257374 : dark theme detection doesn't work in breeze (KDE5 default theme)
- #109 : custom font colors might have little contrast on themed background color

There are some common issues that don't fit there, so I'm opening a new bug report to lay out an idea how to fix this.

Workaround: disable dark theme altogether. gnome-calendar does this. This could be shipped pretty fast.

How to actually fix colors:
- [x] having good theme variant detection working
  - [x] for environment variables: `GTK_THEME=Adwaita:light`
  - [x] for GtkSettings key `gtk-application-prefer-dark-theme`
  - [x] detect other themes which are not Adwaita but might be dark without specifying a dark variant
- [ ] implement some logic to always have enough contrast to background but keep color tendencies, i.e. don't keep the exact RGBA value but allow dark green to become light green, etc.. See also [this W3C spec on how to get contrast right](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html)
- [ ] make sure to get all custom color codes set somewhere.

Alternative approach as [suggested by Gtk+ developer Matthias Clasen](https://bugzilla.gnome.org/show_bug.cgi?id=765629):
- [x] detect theme (as above)
- [ ] load custom CSS files `.installed { color: #darkgreen; }`
- [ ] add style classes like `installed` to those GtkWidgets that need custom themes

This seems to be "the modern Gtk+ 3.x way".
This is nice and clean, but doesn't fix the problem for unknown dark themes without `gtk-application-prefer-dark-theme` set. Gtk+ people don't seem to care about that though.

If nobody objects, I'll be working on this.

**Comment by timlau** [comment]
Agree there is some issues with "Dark" themes, It would be great if you would look into it.

**Comment by genodeftest** [comment]
Theme detection is working: https://gist.github.com/genodeftest/94e623123f20566d158569a2ef3b25a2

**Comment by timlau** [comment]
Dark themes is working fine in current release and support for custom yumex themeing is added
