### ISSUE TITLE
Group installation shows error message though being successful

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#105]
Steps to reproduce:
1. install or remove a group, e.g. "Epiphany Web Browser" below "GNOME Desktop".
2. press the "Apply pending changes" button

What happens:
After typing my password, I get an error dialog with this text:
`Error(s) in building transactiongroup : i : epiphany`

Affected versions:
most recent git master as of now.

**Comment by timlau** [comment]
fixed
