### ISSUE TITLE
yumex-dnf is unable to store (save) repository configuration

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#107]
Steps to reproduce:
1. open yumex-dnf
2. in preferences, disable any repository
3. check "save selected repositories"
4. press "Ok"
5. exit yumex-dnf
6. start yumex-dnf
7. in preferences, have a look at repository configuration

What is expected to happen:
Save configuration for next session

What happens:
Configuration is not saved but reset to defaults.

Additional info:
using yumex-dnf 4.3.2 from copr.

**Comment by timlau** [comment]
fixed
