### ISSUE TITLE
font color of non installed packages

### ISSUE THREAD

**Issue by raveit65** [timlau/yumex-dnf#109]
Yumex-dnf and Yumex set always the font color of non installed packages.
IMO this should not be set, because this is the main cause that it is very hard to read the text with dark backgrounds from dark themes.
The fg and bg colors of view are always set by a theme, so fg color of non installed packages should use this general theme setting.
I don't know if this can work, but i'm happy to test it.
Well, i know this can be set in preferences.

**Comment by genodeftest** [comment]
See #102
