### ISSUE TITLE
[RFE] Show search bar all the time

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#113]
This issue is split off from #108.

In https://github.com/timlau/yumex-dnf/issues/108#issuecomment-219284850, @raveit64 argued for making the search bar always visible.

Cons:
- takes space
- breaks usability of pressing Ctrl+F to show+focus search bar.
  - Idea: remove feature to hide search bar altogether, remove the "show search bar" button. Ctrl+F should just focus the search bar.

Pros:
- Search is a very important feature of a package manager and thus should always be present!

Todo before this can be implemented:
- [ ] Make search available for all views, not just the "packages" view (#112).
- [ ] Redesign search bar to always be visible:
  - [ ] Remove all code hiding it
  - [ ] Remove the "toggle search bar visibility" button from headerbar

Comments?

**Comment by raveit65** [comment]
Maybe you can add a option for this in preferences, so a user can decide for himself to see the searchbar as default in package tab.
In this case it isn't needed to show the toggle button.

Edit:
Who the hell is raveit64? :smile: 
No chance to call me with this name at github.

**Comment by timlau** [comment]
Having an option could be a way, until we get a more generic search bar

**Comment by timlau** [comment]
Added option to show searchbar by default
