### ISSUE TITLE
List installed, available, search by repo 

### ISSUE THREAD

**Issue by biji** [timlau/yumex-dnf#127]
Please add feature to list installed, available, search from a repo only

**Comment by genodeftest** [comment]
I don't understand what you mean. Can you please explain it?

Do you mean something like #89 ?

**Comment by biji** [comment]
Yes, similiar to #89

Equivalent command is:
`dnf repo-pkgs REPO list`
`dnf repo-pkgs REPO list installed`
`dnf repo-pkgs REPO search STRING`

**Comment by genodeftest** [comment]
Closing as duplicate of #89 and suggestions in #74 then.
