### ISSUE TITLE
Package information icon not highlighted on launch

### ISSUE THREAD

**Issue by droidmonkey** [timlau/yumex-dnf#135]
When a package is selected after initial launch, the package information icon is not highlighted. It is sometimes unclear what is being displayed in the package information window. Clicking on an icon highlights it and it will remain in that state until the program is closed.

In addition, it would be nice if the program remembered what information was shown last and on next launch default to that information page. Typically all I care about is WHAT was updated, not all the other package information. I feel like this UI element could use some work, there is a lot of wasted space.

![screenshot1](https://cloud.githubusercontent.com/assets/2809491/17682071/55f9a030-6317-11e6-974a-3d49b74130b3.png)

![screenshot_2016-08-15_18-26-17](https://cloud.githubusercontent.com/assets/2809491/17681861/1b39336c-6316-11e6-931c-f3e4af1710e5.png)

**Comment by genodeftest** [comment]
That's correct, yumex should behave differently.

**Comment by genodeftest** [comment]
Fixed the "no button selected by default" behaviour.

I don't think there is any use in remembering which of the details pages are shown by default.

Which "wasted space"? Do you mean that the details stuff is taking too much screen space? Do you know that you can resize it to be smaller? Or do you want to have package details triggered?

**Comment by droidmonkey** [comment]
Actually after posting that I did resize the details pane and its much better, haha. I don't know why i made it so big relative to the window before. If you fixed the main issue, this can be closed.

**Comment by genodeftest** [comment]
Ok, closing then.
