### ISSUE TITLE
Add better use of keyboard shortcuts

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#14]

**Comment by timlau** [comment]
current upstream has better use of keyboard shortcuts
 * Ctrl - F for seach
 * Alt 1-4 for selection of pages ( Packages, Groups, History & Pending Actions)

**Comment by timlau** [comment]
Needed shortcuts:
 - [ ] package filters (Updates, installed, Available & All) 
 - [ ] package inffo (descriptions, update info, filelist, requirements)
 - [ ] Main menu (Options, help, about, quit and docs)

**Comment by timlau** [comment]
Page for tracking current keyboard shortcuts
https://github.com/timlau/yumex-dnf/wiki/Keyboard-Shortcuts-(4.3.x)

**Comment by genodeftest** [comment]
Gtk+ 3.20 introduced the [GtkShortcutsWindow](https://developer.gnome.org/gtk3/stable/ShortcutsOverview.html) which could be useful here.

**Comment by genodeftest** [comment]
I've added some thoughts on the wiki page.

**Comment by timlau** [comment]
Shortcut has been reworked and GtkShortcutsWindow has been added
