### ISSUE TITLE
fedora24 yumex-dnf is unable to store (save) repository 

### ISSUE THREAD

**Issue by oklokl** [timlau/yumex-dnf#141]
https://github.com/timlau/yumex-dnf/issues/107
Similar symptoms ..

https://youtu.be/mnWP9RAxUhw
my ucc 

yum reinstall yumex-dnf 4.3.3
yumex-dnf.noarch 4.3.3-1.fc24
same..
Linux localhost.localdomain 4.8.8-200.fc24.x86_64
xfce https://labs.fedoraproject.org/security/download/index.html

**Comment by timlau** [comment]
works in current upstream
