### ISSUE TITLE
[Security/Safety] Use privileged dnfdaemon-system only where necessary

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#150]
Currently, dnfdaemon-system is started when yumex-dnf starts and is used for all operations involving dnf such as getting any package list or metadata or search. dnfdaemon-system is running as root and as such is a potential risk of security bugs.

I'd expect yumex-dnf to run without its root backend for most situations.

The only situations where root privileges are required are
* running the real package transaction 
* history access (this might depend on system umask. Can someone please confirm they can run `dnf history info last` and `dnf history list` as ordinary user?)

**Comment by timlau** [comment]
It is a mess to switch between system & session API, metadata has to be loaded twice, memory usage will be much higher etc
