### ISSUE TITLE
Yum extender (DNF) do mistakes when removing packages ?!!

### ISSUE THREAD

**Issue by Nokia808** [timlau/yumex-dnf#155]
Hi. I have an issue (may be issues) with dependencies & post about one of them in Fedora forum & some users said that issue related to Yum extender (DNF) ! I'm not sure & due to the fact that - if true due to error in Yum extender (DNF) -, I decided to post about it here to be evaluated from your side:

Issue as posted by me in Fedora Forum:

 DNF (or PackageKit?) mania ?!!
Hi. I would like to report a phenomenon suffered from yesterday:

Yesterday, & only yesterday, I discovered that Okular is the best viewer/editor for PDF available for free on Linux with 2 surprising features was hidden from me: it support scanned PDF in the fact that after annotating such PDF & save it, it's resolution will never defected, & more surprisingly it's size will never increased what ever you annotating !!!!!!!!!!! And it is opened for great developmental leaps in futures. More over it support CHM files ..... .

So, I decided to uninstall evince (document viewer) because it is bad & seem to be of no powerful development. Here start the story for this thread:

I open Yum extender (DNF) to uninstall evince. I saw 3 installed packages:

- "evince"
- "evince-djvu"
- "evince-libs"

I select package "evince" to remove. 1st thing I saw abnormal is that DNF NOT asked me to remove other 2 packages !!! So, I abort process. I tried to remove package "evince-djvu" alone & DNF not ask me to remove other 2 packages or any other dependencies, & also I aborted this process. Then I tried to remove package "evince-libs" alone. Here DNF ASKED ME TO REMOVE OTHER PACKAGES AS DEPENDENCIES BUT NOT INCLUDING NEITHER "evince" nor "evince-djvu" !!!! Also I aborted this process.

Then I closed Yum extender (DNF) & opened GNOME software center, that I installed on my Fedora Cinnamon edition, & go to evince in this center. I saw that it is installed with add on (plugin) most of them installed by default. I did not see icon to remove evince ! Evince in center was under system programs. I tried just to uninstall 1st plugin (for comic books or files) & after uninstalling this package I tried to uninstall other plugin but I received error message saying that this package NOT ALREADY INSTALLED, but in fact I saw them & evince itself marked in GNOME center as still installed !! I closed software center & reopened Yum extender & here I shocked when I saw all 3 above packages (evince, evince-djvu, evince-libs) are removed in block, but when I returned to GNOME software center I saw evince & all plugin (except plugin that I removed for 1st time) marked as still installed !!

I tried to reinstalled evince from Yum extender. I select only "evince" for installation & DNF asked me for both "evince-djvu" & "evince-libs" as dependencies !!

Then I removed package "evince" only & here DNF NEVER ASKED ME TO REMOVE NEITHER "evince-djvu" nor "evince-libs" as dependencies !! I had similar case that I post as bug in Redhat bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1420468

Then I closed Yum extender & opened terminal & run "sudo dnf autoremove" command (which already psychotic & mad). I aborted it. I run it just to see if it detected "evince-djvu" & "evince-libs" as unnecessary packages BUT IT DID NOT DO THIS ! When it did not recognized these 2 packages as unnecessary this mean that they were used by other package(s) & thus if you try to remove them then you will be asked to remove other package(s) as dependencies or you will received warning message about that or something like this.

I closed terminal & reopened Yum extender again & 1st removed "evince-djvu" & DNF NOT ASKED ME TO REMOVE ANY OTHER PACKAGE (as happened already before), So why this package not removed when I remove evince ??!!!

Then, from Yum extender, I removed "evince-libs". Here is the surprising thing: DNF (oppose to 1st time) NEVER ASKED ME TO REMOVE ANY OTHER PACKAGES AS DEPENDENCIES !!!!! What is this ??!!!

I closed Yum extender & reopened GNOME software center but saw evince & all plugins (except that I removed in 1st trial) marked as installed !!

I closed software center. Then powered off my laptop.

At next boot, I visited GNOME software center to see evince & here it is (with it's plagins) totally disappeared from list of installed applications & packages !!! What is this ??!!!

 It seem that there is(are) real problem(s) in either DNF or PackageKit or both of them, which cause this mania ??!!! 

source on Fedora Forum:
http://www.forums.fedoraforum.org/showthread.php?t=313529

Please read replays in above thread in Fedora Forum. I will post 2 of them (by antikythera):

1) "dnf is not the problem here, yumex-dnf is.
you are talking about yumex-dnf issues here that do not affect the command line utility dnf itself. the problem is in yumex-dnf which is rubbish at handling dependencies as you have now found for yourself. I always use dnf where I haven't installed the more reliable deprecated version of yumex from copr. ........."

2) "for some reason though it really does produce different results. if you remove a package using yumex-dnf it sometimes leaves the dependencies even if you set it up to erase them in preferences. dnf from the command line for whatever reason is much more reliable in that respect. i think it may be to do with how yumex-dnf handles metadata.
also, yumex-dnf will often fail to complete an update transaction due to what it thinks are broken dependencies. whereas instructing dnf from the command line to update the system works fine."
-------------------------

Please evaluate this issue & accept my sorry if it is not a bug related to Yum extender (DNF). Really I'm not sure !

**Comment by genodeftest** [comment]
I answered on your Fedora bug report, please keep it there: https://bugzilla.redhat.com/show_bug.cgi?id=1420468#c3 . Only with the debugdata we can get a look on what went wrong.
Anyway, it might be that your system is so messed up that you need to reinstall your Fedora.

And yes, yumex-dnf is behaving badly in some situations. I added a more general bug report on that in #157.
