### ISSUE TITLE
Not a fan of useless buttons

### ISSUE THREAD

**Issue by Plutonium5793** [timlau/yumex-dnf#156]
Perhaps you can tell me why with this yumex I have to click on a button way up in the corner just to get the search text box.  Why not have the search text box available all the time as in the older version?
There is plenty of window real estate, and that is all the one button does is tell the program I want to search. It could figure that out when I click on the search box.   I am a fan of less useless mouse clicks.
Thanks,
John

**Comment by timlau** [comment]
You can use Ctrl-F to show and hide the search bar.
