### ISSUE TITLE
Advise against using yumex-dnf for actual package transactions

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#157]
There are a number of quite massive problems with yumex-dnf, some of them with many details unclear: #155 #129 and the big list on https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&component=yumex-dnf&list_id=7196025&product=Fedora&query_format=advanced

Even I (as a  contributor) stopped using yumex-dnf for actual package transactions, because it broke too often. And I don't have time or interest to get all those bugs reported or fixed.

Since there is no manpower to get those bugs fixed in time I suggest disabling the "update" feature and reducing the yumex-dnf feature set to reading package metadata (incl. search) and reading the package database.

If we can't do that, I will suggest deprecating and removing yumex-dnf from Fedora repositories, because it might cause too much harm to people using it.

**Comment by timlau** [comment]
Hi Christian
 I have not been able to find the time to maintain yumex-dnf for a long periode of time, so i have deceided to stop the project and orphan it from Fedora.

Thanks a lot for all the help from you and other contributors.

If someone steps up and will take over the project, then i will give them access to there repositories

Thanks

Tim Lauridsen

**Comment by timlau** [comment]
Most things works fine with current versions of dnf & dnfdaemon
