### ISSUE TITLE
Fedora Coprs repo

### ISSUE THREAD

**Issue by raveit65** [timlau/yumex-dnf#165]
Hi can you please enable build for arm (32/64bits) in your coprs repo?
I forked your repo and installed yumex-dnf on a Raspberry Pi with fedora xfce/Mate without any problem.
https://copr.fedorainfracloud.org/coprs/raveit65/yumex-dnf/
2 repos with the same version of yumex-dnf seems a bit overload.

**Comment by timlau** [comment]
Nice, I will add ARM builds to my copr repo

**Comment by timlau** [comment]
archs added and rebuilds done 
https://copr.fedorainfracloud.org/coprs/timlau/yumex-dnf/build/2682801/
https://copr.fedorainfracloud.org/coprs/timlau/yumex-dnf/build/2682799/

**Comment by raveit65** [comment]
Thank you :)
