### ISSUE TITLE
Release for Fedora 36

### ISSUE THREAD

**Issue by SkeleySash** [timlau/yumex-dnf#169]
This isn't really an issue but more of a hopeful request. 

I was hoping you'd be preparing for a release build in time for Fedora 36.

**Comment by timlau** [comment]
I have just started new copr builds including the f36 build roots

**Comment by timlau** [comment]
Both yumex-dnf and dnfdaemon is now build for F36

https://copr.fedorainfracloud.org/coprs/timlau/yumex-dnf/build/3811354/
https://copr.fedorainfracloud.org/coprs/timlau/yumex-dnf/build/3811356/
