### ISSUE TITLE
Minimum window height makes Yumex difficult to use on low resolution screens

### ISSUE THREAD

**Issue by JohanAR** [timlau/yumex-dnf#171]
Installed Nobara Project Linux in a VM. I don't think they've modded Yumex in any way, but in case they have and this problem is distro specific I apologize in advance..

The VM defaults to a resultion of 1024 x 768, and the Yumex window appears to have a larger minimum height than 768 so it's impossible to fit it on the screen. Looks like neither the package list and package description needs this much space so hopefully it's an easy fix for someone who knows their way around the code.

**Comment by timlau** [comment]
yumex is designed to have a min. size at 800x800

You can try to change it in the yumex.ui file, but it make break things :-D

❯ grep -e 800 -n  data/ui/yumex.ui 
120:    <property name="width-request">800</property>
121:    <property name="height-request">800</property>

**Comment by JohanAR** [comment]
Any possibility that it could be changed to minimum 800x600? I don't think it looks like it need that much height for anything

**Comment by bassnfool2** [comment]
I have modified the yumex.ui file to change the minimum resolution to 800x600.  I have testind it and found no errors and yumex-dnf now works much better on my laptop's 1366x768 resolution.  Prior to this change the minimize/maximize button was not visible.  Once this change was made, the minimize/maximize button was visible.  I would say that it would be useful to change this to the default.

**Comment by timlau** [comment]
Thanks for testing, I will change it 800x600

**Comment by bassnfool2** [comment]
awesome thanks!
