### ISSUE TITLE
Text colors are too light for light theme 

### ISSUE THREAD

**Issue by bassnfool2** [timlau/yumex-dnf#177]
The text colors are very hard to read when using the light theme.  Below are the changes I made:

--- a/misc/themes/System-Light.theme
+++ b/misc/themes/System-Light.theme
@@ -1,9 +1,9 @@
 /*Package Type Colors */
-@define-color color_install     #3F51B5;
+@define-color color_install     #0319AB;
 @define-color color_update      #E91E63;
 @define-color color_downgrade   #CDDC39;
-@define-color color_normal      #FF9800;
-@define-color color_obsolete    #4CAF50;
+@define-color color_normal      #AB2A03;
+@define-color color_obsolete    #4CAE54;

**Comment by timlau** [comment]
Can you please make a pull request and I will test the new colors

/Tim

**Comment by bassnfool2** [comment]
pull request completed

**Comment by timlau** [comment]
PR merged
