### ISSUE TITLE
Little typo in  "management"

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-dnf#181]
Yumex --help 

usage: yumex [-h] [-d] [--exit]

Yum Extender package managemnt application

**Comment by timlau** [comment]
Thanks for reporting, even if then wrong project, should be in https://github.com/timlau/yumex-ng ;.D

fixed in:
https://github.com/timlau/yumex-ng/commit/f34bae18a88243c4feed284cd4d4f1769505865a

**Comment by edpil02** [comment]
Sorry . I also made a typo in my browser   : I typed    yumex-dnf  instead of yumex-ng
But thanks for porting dnf5  in   yumex
