### ISSUE TITLE
theming questions

### ISSUE THREAD

**Issue by NiceandGently** [timlau/yumex-dnf#26]
I want to style yumex-dnf a bit with mate-themes. Normaly this is quite easy with using gk3-inspector to find the right widget, but i have some probs.
ie.  the toolbar.
```
.background .vertical .horizontal {
        background-image: linear-gradient(to bottom,
	                                  @toolbar_gradient_base,
	                                  @toolbar_gradient_bottom);
	border-style: none;
	border-width: 3px;
	border-radius: 0px;
	padding: 10px;
	-GtkWidget-window-dragging: true;
	-GtkToolbar-button-relief: normal;
}
```
This works but needs to be more specific because i want only style yumex, not any other application.
According to what gtk3-inspector shows is the extended line this one.
```
yumex+YumexWindow.background GtkBox.vertical yumex+YumexToolbar.horizontal {
```
But this fails, same with
```
YumexWindow.background .vertical .horizontal {
```
or
```
yumex.background .vertical .horizontal {
```
I  never saw widget names like 'yumex+YumexWindow' or 'yumex+YumexToolbar'  for gtk3 apps with gtk3-inspector. Normaly a widget is called ie. 'NautiusWindow', without a second expression.
Maybe this is the problem?

symbolic icons vs. regular icons
Since gtk+-3.14 it is possible to force applications to use regular icons with the theme, if a regular icon exists in the icon theme.
This is what we do with '-gtk-icon-style: regular' in MATE with fortcomming 1.10 release, see https://mail.gnome.org/archives/gtk-devel-list/2014-May/msg00020.html
This works brilliant with yumex, exept with the 'system-run[symbolic]' icon.
This icon use GtkButton widget, all other icons use GtkMenuButton widget.
I'm quessing if the icon would use the GtkMenuButton widget too than the normal regular will display with a mate theme.
![yumextender-nautilus-changed-icons](https://cloud.githubusercontent.com/assets/961604/7353300/ca066502-ed12-11e4-8cfd-f0194bdc6511.png)

So, maybe you can help me.

**Comment by NiceandGently** [comment]
Ok, i could solve the question about the icon , system-run-symbolic.symbolic.png is needed in regular icon theme.

**Comment by timlau** [comment]
I have changed the Execute button to use GtkMenuButton.

Look like the namming comes from how the the class is names in Python

YumexWindow class in yumex module, gets the name yumex+YumexWindow.

Dont know much about theming, I have added at application id 'apps.yumex-dnf', dont know if it helps, but i have see gtk themes having application specific styling like this
https://github.com/shimmerproject/Greybird/blob/master/gtk-3.0/apps/synaptic.css

dont know if it is based on the application id.

**Comment by timlau** [comment]
yumex load it own custom css gtk-style.css located in the data dir (/usr/share/yumex-dnf) it is blank by default, try play around with that, if it solves your need, Then i can make some changes to load it from /etc/yumex-dnf/gtk-style.css if this exits

**Comment by timlau** [comment]
I have changed the Execute button back to use GtkButton, this was not the issue
fixed the icon name to 'system-run-symbolic', it was named 'system-run-symbolic.symbolic'

**Comment by NiceandGently** [comment]
yeah, https://github.com/timlau/yumex-dnf/commit/1789a5cab73de4928f06ff25b5708c2e52926b92 fixes the usage of regular icons :) , thanks.
I will test to use a custom gtk-style.css.
Also, i will ask gtk+ guys how to handle style widegs like yumex+YumexWindow.
If it comes from python, yumex-dnf wouldn't be the only application which is affected.

**Comment by NiceandGently** [comment]
Using a application id 'apps.yumex-dnf doesn'help for widgets names.

**Comment by timlau** [comment]
found this
http://wolfvollprecht.de/blog/gtk-python-and-css-are-an-awesome-combo/

I have set the styling name to 'YumexMainWindow', Hope it helps you

**Comment by NiceandGently** [comment]
Unfortunately this doesn't help, same sittuation.
All specific widget names in css will be ignored.
But i could write a gtk-style.css (for a dark theme), it's very limmited because here i've the same problem that unspecific widget names override styles other widgets too.
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/gtk-style.css
Here i increased the button size, but in a next step i needed to correct the colum-button size ;)
But theming only yumex is a progress.
Is it possible that yumex read such a file from user directory?
ie. ~.local/share/yumex-dnf/
Than i can ship such a file with the theme package and a user can copy it by hand.
Imo, that's better than somewhere in /etc, because a theme can change by a user.

**Comment by timlau** [comment]
what about providing a
/usr/share/themes/<name>/gtk-3.0/apps/yumex.css

then I will look for /usr/share/themes/<current theme>/gtk-3.0/apps/yumex.css and use it if it exists

**Comment by NiceandGently** [comment]
> what about providing a
> /usr/share/themes//gtk-3.0/apps/yumex.css
>
> then I will look for /usr/share/themes/theme-name/gtk-3.0/apps/yumex.css and use it if it exists

Great idea!
+1

**Comment by timlau** [comment]
Looking for the following styling files
~/.themes/**name**/gtk-3.0/apps/yumex.css
/usr/share/themes/**name/gtk-3.0/apps/yumex.css

**name** is current theme

**Comment by NiceandGently** [comment]
imo it should be better for home folder to look at ~.themes/**name/apps/yumex
or is this to complicated?

**Comment by NiceandGently** [comment]
perfect, i will test this

**Comment by timlau** [comment]
Do you mean looking for ~/.themes/name/apps/yumex.css instead of ~/.themes/name/gtk-3.0/apps/yumex.css ?

**Comment by NiceandGently** [comment]
yes

**Comment by timlau** [comment]
changed

**Comment by NiceandGently** [comment]
All is working, yumex.css loads from both places :)
Some screenshots with BlackMATE theme.
![yumex-dnf-infobar](https://cloud.githubusercontent.com/assets/961604/7399075/6ea0013a-eeb3-11e4-80c4-abc02b414d1c.png)
![yumex-dnf-packageview](https://cloud.githubusercontent.com/assets/961604/7399083/786d11bc-eeb3-11e4-9429-326af45b628e.png)
![yumex-dnf-groupview](https://cloud.githubusercontent.com/assets/961604/7399132/d7139448-eeb3-11e4-97df-e9e32e03b6a6.png)
Thank you!

PS: I will yumex-dnf to mate group for f22

**Comment by timlau** [comment]
Looks nice
