### ISSUE TITLE
Crash   on dnf  error

### ISSUE THREAD

**Issue by eddy02** [timlau/yumex-dnf#3]
Yumex crash today when trying to update rawhide : 
---
File "/usr/lib/python3.4/site-packages/dnfdaemon/server/__init__.py", line 531, in run_transaction
    self.base.do_transaction(display=display)
  File "/usr/lib/python3.4/site-packages/dnf/base.py", line 542, in do_transaction
    self.errorSummary(errstring))
AttributeError: 'DnfBase' object has no attribute 'errorSummary'
 (36
---
Using  dnf cli  command  sent   a conficting files packages  (procps-ng-3.3.10-1.fc22) 
Seem likely that yumex  crash  on conficting packages error.

Thanks , and sorry for my poor english.

**Comment by timlau** [comment]
fixed in upstream dnf
