### ISSUE TITLE
changing the the newest only should trigger a search update

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#30]
if you search for ex. **yumex**, with **newest only** active and uncheck **newest only**
then yumex-dnf should search again for **yumex**

**Comment by kn00tcn** [comment]
is this broken? on f25 i see the results disappear & the search field empty when i toggle the option after freshly opening yumex & searching first thing

at one point the toggle didnt clear the list, but not quite sure how i triggered that
