### ISSUE TITLE
Search does not default to "any position"

### ISSUE THREAD

**Issue by droidmonkey** [timlau/yumex-dnf#32]
The search behavior in yumex-dnf is inconsistent with dnf search. Search should not force finding at the start of a string to return a result if "prefix" is selected. A search string should return if found in any part of the prefix. The current behavior requires the prepending of an * to all search terms.

**Comment by timlau** [comment]
I don't see the problem

The differnt type of search work like this

prefix = search for key* in name
keyword = search for *key* in name
fields = search  for key in selected fields (name, summary, description.)

The selected search type is saved between seesion, so you just have to select keywordm that sounds like the search type you want.

**Comment by droidmonkey** [comment]
Good point, this issue can be closed.
