### ISSUE TITLE
Post-pone the update notification

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#40]
*Usecase:*

If the user get a notification about pending updates, there should be a way to post-pone the notification if the user dont want to update this point in time and don't want a new notification next time updates is checked.

This could be implemented by adding a ignore button to the update notification and add a setting in preferences to specify the time the update notification is post-poned, when ignore is pressed.

**Comment by timlau** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1224941

**Comment by rapgro** [comment]
:+1:

**Comment by timlau** [comment]
Done in resigned update checker
