### ISSUE TITLE
Too dark on GNOME Shell's Dark Theme

### ISSUE THREAD

**Issue by injcristianrojas** [timlau/yumex-dnf#42]
Hi,

I've just installed Fedora 22, and I'm using the Dark Theme option on GNOME Shell's Tweak Tool (Global Dark Theme). When using Yumex-DNF it looks like this: Too dark:

![screenshot from 2015-05-28 13-21-52](https://cloud.githubusercontent.com/assets/862690/7865070/885a2b10-053c-11e5-8ccf-5b64409e287a.png)

**Comment by timlau** [comment]
Looks link the default text color dont look good in a dark theme.

**Comment by timlau** [comment]
https://github.com/timlau/yumex-dnf/commit/21f09d1d514578074b4e5f200a05cd58e5d467b2
 should fix this
