### ISSUE TITLE
check that the right version of dnfdaemon & statusicon daemon is running

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#43]
yumex-dnf should check that the right version of dnfdaemon is running.

properly at good idea to add a API version returned by GetVersion, that can be dumped on API changes for both D-Bus daemons.

**Comment by timlau** [comment]
done

**Comment by rapgro** [comment]
This could happen when dnfdaemon-system is still running as root, I logged off and login again but the daemon seems to survive and I killed it manually. Yumex-dnf restarted a new root process and works then.
See also https://github.com/timlau/yumex-dnf/issues/44

**Comment by timlau** [comment]
@rapgro yes, this the system dbus service run as root, it has a build in watchdog there will terminate it when not working and not use for 20s, so it will not be closed if the user logs off, because it is a system service.
This change will make it possible to detect what API version the different daemons used by yumex-dnf, so we don't try to do any not supported.
One reason is dnfdaemon or yumex-dnf is updated, bu the old version is still running (this is what #44 is about)
Another way is is yumex-dnf is downgrade, but dnfdaemon is not.
