### ISSUE TITLE
yumex should restart statusicon, when upgrading itself

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#44]
when statusicon is set to autostart and yumex-dnf update itself and the user closes the gui
then the old version statusicon is still running and if there is some api changes, then yumex-dnf might fail if the statusicon applet is not quited.

**Comment by rapgro** [comment]
This could happen when dnfdaemon-system is still running as root, I logged off and login again but the daemon seems to survive and I killed it manually. Yumex-dnf restarted a new root process and works then.

**Comment by genodeftest** [comment]
Wouldn't it be easier to use GtkApplication to make sure that only one instance of yumex-dnf is running? In this case the dbus part could be moved into yumex-dnf, so only one application running as user is being left.
GApplication doesn't need to have a window running, see e.g. nautilus on Gnome 3.16/3.18. In this case you wouldn't need to check the statusicon version in yumex-dnf.

**Comment by timlau** [comment]
The idea with the separate StatusIcon app was to have a small memory footprint app there can check for updates and launch the gui on user request.
It is also uses to checked if another version is already running, this part can properly be implemented in GtkApplication, but the docs for using GtkApplication in python is not the best, when I tarting to use it, but it can have been improved since.

**Comment by timlau** [comment]
Fixed in the current 4.3.x development versions

Se #79 for details
