### ISSUE TITLE
Error(s) in search for dependencies

### ISSUE THREAD

**Issue by tsingi** [timlau/yumex-dnf#47]
Since the upgrade to Fedora 22 I get this when I try to update with yumex-dnf.  It's reminiscent of the windows error "The parameter is incorrect" in that it leaves you with little that is useful information.

Running dnf from the command line as root found that there was a non-responsive mirror and then it moved on to a good one and completed successfully updating 239 packages.  I don't know if the bad mirror was the problem with the gui.

I've had warnings that 'updates' appears more than once in the repo list.  Not my deliberate doing but another possible gotcha.

**Comment by timlau** [comment]
what version of yumex-dnf and dnfdaemon are you running ?

**Comment by tsingi** [comment]
Tried starting it yesterday afternoon and it racked up 96% cpu but did not
come up for 10 minutes.  Went home.  This morning top is still running,
yumex-dnf isn't.  I try to run it from the command line I get a warning
that it is still running.  Lock?  ps shows no process called yumex-anything

Try to run it from menu, get gui and warning.  Looks like it crashed.

Dmesg has this in it...

[88075.414107] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88075.414132] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88075.414142] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88075.414201] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88075.414212] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88075.414221] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88075.432689] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88075.432710] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88075.432720] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88075.447262] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
#366386: comm yumex-dnf: reading directory lblock 0
[88103.908258] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
error -5 reading directory block (ino 366386, block 0)
[88103.910152] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
error -5 reading directory block (ino 366386, block 0)
[88327.075835] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
error -5 reading directory block (ino 366386, block 0)
[88343.663183] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
error -5 reading directory block (ino 366386, block 0)
[21042.180551] show_signal_msg: 9 callbacks suppressed
[21042.180560] yumex-dnf[5368]: segfault at 7fff1feb7ff8 ip
00007f1b727d4af1 sp 00007fff1feb8000 error 6 in libc-2.21.so
[7f1b72751000+1b6000]

Yup, it crashed.

I suppose there is an install log/db somewhere where I can look up the
version number?  Ordinarily I would run the program and ask it, or run
yumex and look at installed packages.

It was installed after a fedora 22 update within the last week or ten days.






On Wed, Jun 10, 2015 at 1:06 PM, Tim Lauridsen <notifications@github.com>
wrote:

> what version of yumex-dnf and dnfdaemon are you running ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timlau/yumex-dnf/issues/47#issuecomment-110837051>.
>



-- 
"Capitalism creates the elite and crashes on a regular basis, it's far from
a perfect system."
 - Me

**Comment by tsingi** [comment]
/var/log/messages

[root@euclid log]# grep yumex messages
Jun 10 08:54:57 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
('google-chrome', 0.0)
Jun 10 08:54:57 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
('google-chrome', 1.0)
Jun 10 08:54:57 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
('google-chrome', 1.0)
Jun 10 08:58:52 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
('google-chrome', 0.0)
Jun 10 08:58:52 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
('google-chrome', 1.0)
Jun 10 08:58:52 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
('google-chrome', 1.0)
Jun 10 09:42:14 bill-xps dk.yumex.StatusIcon: (dbus_status.py:3420):
Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2769:41: Expected a
valid selector
Jun 10 14:02:56 bill-xps audit: <audit-1701> auid=1000 uid=1000 gid=1000
ses=1 pid=5368 comm="yumex-dnf" exe="/usr/bin/python3.4" sig=11
Jun 10 14:02:56 bill-xps kernel: yumex-dnf[5368]: segfault at 7fff1feb7ff8
ip 00007f1b727d4af1 sp 00007fff1feb8000 error 6 in libc-2.21.so
[7f1b72751000+1b6000]
Jun 11 08:40:10 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0
Jun 11 08:40:10 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0
Jun 11 08:40:10 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0
Jun 11 08:40:10 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0
Jun 11 08:40:11 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0
Jun 11 08:40:11 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0
Jun 11 08:40:11 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0
Jun 11 08:40:11 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0
Jun 11 08:40:12 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0
Jun 11 08:40:12 bill-xps kernel: EXT4-fs error (device sdc2):
ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
lblock 0


On Thu, Jun 11, 2015 at 8:55 AM, Rick <graham.rick@gmail.com> wrote:

> Tried starting it yesterday afternoon and it racked up 96% cpu but did not
> come up for 10 minutes.  Went home.  This morning top is still running,
> yumex-dnf isn't.  I try to run it from the command line I get a warning
> that it is still running.  Lock?  ps shows no process called yumex-anything
>
> Try to run it from menu, get gui and warning.  Looks like it crashed.
>
> Dmesg has this in it...
>
> [88075.414107] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88075.414132] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88075.414142] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88075.414201] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88075.414212] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88075.414221] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88075.432689] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88075.432710] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88075.432720] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88075.447262] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
> #366386: comm yumex-dnf: reading directory lblock 0
> [88103.908258] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
> error -5 reading directory block (ino 366386, block 0)
> [88103.910152] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
> error -5 reading directory block (ino 366386, block 0)
> [88327.075835] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
> error -5 reading directory block (ino 366386, block 0)
> [88343.663183] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
> error -5 reading directory block (ino 366386, block 0)
> [21042.180551] show_signal_msg: 9 callbacks suppressed
> [21042.180560] yumex-dnf[5368]: segfault at 7fff1feb7ff8 ip
> 00007f1b727d4af1 sp 00007fff1feb8000 error 6 in libc-2.21.so
> [7f1b72751000+1b6000]
>
> Yup, it crashed.
>
> I suppose there is an install log/db somewhere where I can look up the
> version number?  Ordinarily I would run the program and ask it, or run
> yumex and look at installed packages.
>
> It was installed after a fedora 22 update within the last week or ten days.
>
>
>
>
>
>
> On Wed, Jun 10, 2015 at 1:06 PM, Tim Lauridsen <notifications@github.com>
> wrote:
>
>> what version of yumex-dnf and dnfdaemon are you running ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/timlau/yumex-dnf/issues/47#issuecomment-110837051>.
>>
>
>
>
> --
> "Capitalism creates the elite and crashes on a regular basis, it's far
> from a perfect system."
>  - Me
>
>
>


-- 
"Capitalism creates the elite and crashes on a regular basis, it's far from
a perfect system."
 - Me

**Comment by tsingi** [comment]
after reboot and forcing an fschk I have yumex-dnf starting

VERSIONS

yumex 3.0.17-1.fc22
yumex-dnf 4.1.2-1.fc22
dnf 1.0.0-1.fc22
dnf-daemon 0.3.8-1.fc22

On Thu, Jun 11, 2015 at 9:50 AM, Rick <graham.rick@gmail.com> wrote:

>
> /var/log/messages
>
> [root@euclid log]# grep yumex messages
> Jun 10 08:54:57 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
> ('google-chrome', 0.0)
> Jun 10 08:54:57 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
> ('google-chrome', 1.0)
> Jun 10 08:54:57 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
> ('google-chrome', 1.0)
> Jun 10 08:58:52 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
> ('google-chrome', 0.0)
> Jun 10 08:58:52 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
> ('google-chrome', 1.0)
> Jun 10 08:58:52 bill-xps dk.yumex.StatusIcon: on_RepoMetaDataProgress :
> ('google-chrome', 1.0)
> Jun 10 09:42:14 bill-xps dk.yumex.StatusIcon: (dbus_status.py:3420):
> Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2769:41: Expected a
> valid selector
> Jun 10 14:02:56 bill-xps audit: <audit-1701> auid=1000 uid=1000 gid=1000
> ses=1 pid=5368 comm="yumex-dnf" exe="/usr/bin/python3.4" sig=11
> Jun 10 14:02:56 bill-xps kernel: yumex-dnf[5368]: segfault at 7fff1feb7ff8
> ip 00007f1b727d4af1 sp 00007fff1feb8000 error 6 in libc-2.21.so
> [7f1b72751000+1b6000]
> Jun 11 08:40:10 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
> Jun 11 08:40:10 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
> Jun 11 08:40:10 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
> Jun 11 08:40:10 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
> Jun 11 08:40:11 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
> Jun 11 08:40:11 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
> Jun 11 08:40:11 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
> Jun 11 08:40:11 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
> Jun 11 08:40:12 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
> Jun 11 08:40:12 bill-xps kernel: EXT4-fs error (device sdc2):
> ext4_find_entry:1289: inode #366386: comm yumex-dnf: reading directory
> lblock 0
>
>
> On Thu, Jun 11, 2015 at 8:55 AM, Rick <graham.rick@gmail.com> wrote:
>
>> Tried starting it yesterday afternoon and it racked up 96% cpu but did
>> not come up for 10 minutes.  Went home.  This morning top is still running,
>> yumex-dnf isn't.  I try to run it from the command line I get a warning
>> that it is still running.  Lock?  ps shows no process called yumex-anything
>>
>> Try to run it from menu, get gui and warning.  Looks like it crashed.
>>
>> Dmesg has this in it...
>>
>> [88075.414107] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88075.414132] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88075.414142] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88075.414201] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88075.414212] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88075.414221] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88075.432689] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88075.432710] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88075.432720] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88075.447262] EXT4-fs error (device sdc2): ext4_find_entry:1289: inode
>> #366386: comm yumex-dnf: reading directory lblock 0
>> [88103.908258] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
>> error -5 reading directory block (ino 366386, block 0)
>> [88103.910152] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
>> error -5 reading directory block (ino 366386, block 0)
>> [88327.075835] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
>> error -5 reading directory block (ino 366386, block 0)
>> [88343.663183] EXT4-fs warning (device sdc2): __ext4_read_dirblock:884:
>> error -5 reading directory block (ino 366386, block 0)
>> [21042.180551] show_signal_msg: 9 callbacks suppressed
>> [21042.180560] yumex-dnf[5368]: segfault at 7fff1feb7ff8 ip
>> 00007f1b727d4af1 sp 00007fff1feb8000 error 6 in libc-2.21.so
>> [7f1b72751000+1b6000]
>>
>> Yup, it crashed.
>>
>> I suppose there is an install log/db somewhere where I can look up the
>> version number?  Ordinarily I would run the program and ask it, or run
>> yumex and look at installed packages.
>>
>> It was installed after a fedora 22 update within the last week or ten
>> days.
>>
>>
>>
>>
>>
>>
>> On Wed, Jun 10, 2015 at 1:06 PM, Tim Lauridsen <notifications@github.com>
>> wrote:
>>
>>> what version of yumex-dnf and dnfdaemon are you running ?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/timlau/yumex-dnf/issues/47#issuecomment-110837051>.
>>>
>>
>>
>>
>> --
>> "Capitalism creates the elite and crashes on a regular basis, it's far
>> from a perfect system."
>>  - Me
>>
>>
>>
>
>
> --
> "Capitalism creates the elite and crashes on a regular basis, it's far
> from a perfect system."
>  - Me
>
>
>


-- 
"Capitalism creates the elite and crashes on a regular basis, it's far from
a perfect system."
 - Me

**Comment by NiceandGently** [comment]
I can confirm that too in f22 with latest version.
Today it shows me a update about 96 packages but i could not apply them.
A error message poped up , something about 'could not apply keys'.
With 'dnf update' in a terminal the update runs fine without any problem.
I'm really missing the log page from old yumex which shows us what's going on if a update failed.
Without this page it's very hard to say what's going on.
Note, i saw this issue very often in the last weeks.

**Comment by timlau** [comment]
Please read here how to debug issues.

http://yumex-dnf.readthedocs.org/en/latest/faq.html#debug-issues-in-yum-extender

And submit the output from the 2 terminals

**Comment by timlau** [comment]
Please re-test with 4.1.4, there is some changes in the dnfdaemon  there will properly fix this

**Comment by timlau** [comment]
@raveit65 :could not apply keys' is fixed, See #71 for details

**Comment by raveit65** [comment]
nice,
but personal i don't use yumex-dnf anymore....
.... most issues seems to be related to dnf itself.....so i prefer yum-deprecated
