### ISSUE TITLE
yumex-dnf doesn't honor dnf-plugin versionlock

### ISSUE THREAD

**Issue by raveit65** [timlau/yumex-dnf#48]
I use new dnf-plugin versionlock to avoid updating to broken gtk3-3.16.5-1, see https://bugzilla.gnome.org/show_bug.cgi?id=752184#c6
But yumex-dnf ignore settings in /etc/dnf/plugins/versionlock.list

**Comment by timlau** [comment]
The problem here is dnf plugins is extentions to the dnf cli, when using dnf API, then these plugins is not loaded at all.

yum had diffent types of plugins, dnf don't
