### ISSUE TITLE
yumex-dnf not excluding excludes from dnf.conf

### ISSUE THREAD

**Issue by cslux** [timlau/yumex-dnf#50]
I added some packages to the exclude list in dnf.conf which should not be updated. However, yumex-dnf still includes them.

Has yumex-dnf a separate configuration file to achieve the same.

Thanks.

**Comment by timlau** [comment]
Fix in latest release of dnfdaemon, will hit the repos soon

https://github.com/timlau/dnf-daemon/commit/f45231c3707c46be6f7d3234b236550f50fc6793

**Comment by cslux** [comment]
Hey,

sorry for the late reply. Actually thought it will take just a few days until it lands in the fedora-uptades repo, but still not there. Quickly tested it from the fedora-updates-testing repo and the problem is solved, thanks.

regards
