### ISSUE TITLE
Yumex statusbar icon is non-functional following resume from sleep

### ISSUE THREAD

**Issue by droidmonkey** [timlau/yumex-dnf#51]
After performing a successful update and sending Yumex to the status bar it will come back without an issue. Once the computer goes to sleep and wakes again, however, it will not re-open and when prompted to kill yumex upon relaunch, nothing happens (ie, it doesn't get killed).

Running:
Fedora-22
xfce
Yumex-DNF 4.1.2

Killing this process in task manager lets me launch Yumex again:

/usr/bin/python3 -tt /usr/share/yumex-dnf/dbus-status.py

**Comment by droidmonkey** [comment]
When run in debug mode in console and trying to start a "package installation" by double clicking an rpm file I get the following error:

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

and the dialog box to kill Yumex-DNF. If I press NO it still kills yumex but leaves the dbus-status.py process running leaving me in the same state as the above commentary.

**Comment by droidmonkey** [comment]
I have not been able to replicate this behavior in the past 3 days, I think something fixed it. Tempted to close the issue at this point.

**Comment by genodeftest** [comment]
I can't see this issue either. Running yumex-dnf-4.1.4-1.fc22.noarch

**Comment by timlau** [comment]
closing, please reopen if it happen again
