### ISSUE TITLE
[rfe] reduce default logging. Is default loglevel set to debug?

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#52]
In default loglevel in a fedora 22 or 23 installation, yumex-dnf does quite a lot logging. Most of that is not needed imho and just clutters the log file. This is so much logging that I got a message from systemd-journald: `systemd-journal[559]: Suppressed 7158 messages from /user.slice/user-1000.slice` for downloading just one single file.

This logging includes:
* `on_RepoMetaDataProgress` [src/yumex/dnf_backend.py#L269](https://github.com/timlau/yumex-dnf/blob/23dd01465964479459e708a5a2cdd30ac1d0114f/src/yumex/dnf_backend.py#L269)
* `on_DownloadProgress` [src/yumex/dnf_backend.py#L252](https://github.com/timlau/yumex-dnf/blob/23dd01465964479459e708a5a2cdd30ac1d0114f/src/yumex/dnf_backend.py#L252)
* `on_DownloadEnd` [src/yumex/dnf_backend.py#L259](https://github.com/timlau/yumex-dnf/blob/23dd01465964479459e708a5a2cdd30ac1d0114f/src/yumex/dnf_backend.py#L259)
* `on_DownloadStart` [src/yumex/dnf_backend.py#L241](https://github.com/timlau/yumex-dnf/blob/23dd01465964479459e708a5a2cdd30ac1d0114f/src/yumex/dnf_backend.py#L241)
* `RPMProgress : verify <packagename>` (how about logging only on errors or warnings?)
I don't think there is any need for this in ordinary use cases. The on_Download* texts seem to be fixed in master (but not in the versions currently shipped with fedora).

There is a few of those entries in syslog:
```
dk.yumex.StatusIcon[1703]: TransactionEvent : start-build
dk.yumex.StatusIcon[1703]: Data :
dk.yumex.StatusIcon[1703]: null
```
from [src/yumex/dnf_backend.py#L218](https://github.com/timlau/yumex-dnf/blob/23dd01465964479459e708a5a2cdd30ac1d0114f/src/yumex/dnf_backend.py#L218) with different `TransactionEvent`s such as:
* start-build
* end-build
* start-run
* pkg-to-download
* signature-check
* run-transaction
* verify
* end-run
Since line 2 and 3 are meaningless, I think they could be omitted or just appended to the first line.
* download

To me this looks like the default log level is set to DEBUG, which seems weird. Can you please lower the default loglevel? Or is this a communication issue between yumex-dnf and journald?

**Comment by genodeftest** [comment]
There is another entry I see thousands of times in syslog:
`org.baseurl.DnfSystem[854]: DBG:  <dnf.yum.history.YumHistoryTransaction object at 0xSOMETHING timestamp`

**Comment by timlau** [comment]
Look like I have some leftover print statement in the backend daemons

**Comment by timlau** [comment]
52
