### ISSUE TITLE
Document or create an easy way to test yumex

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#57]
Is there an easy way to test the yumex frontend without having to package it and install the package locally? I am thinking of something like `python3 ./src/main.py` which fails due to something with versions I don't understand. For UI development it would be helpful to have an easy one-line command to run yumex.

**Comment by timlau** [comment]
There need some docs on this, I most cases it is just runn python ./src/main.py but if the current checkout need som dnfdaemon changes, then you need to start the daemon manually from a terminal from a dnf-daemon checkout (hint: the Makefile has targets for running the daemons from a checkout)

https://github.com/timlau/dnf-daemon/blob/master/Makefile#L192

**Comment by genodeftest** [comment]
I've created this wiki page:
https://github.com/timlau/yumex-dnf/wiki/Testing-yumex-dnf-for-developing
and am closing this issue. Feel free to reopen if someone misses something.

**Comment by timlau** [comment]
Nice, thanks
