### ISSUE TITLE
[RFE] [User experience] [history view] automatically expand to latest history entry

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#67]
In history view it would be nice to expand the tree (left side) to the latest entry, select it and display its contents. Also expand the list of installed, updated, removed, … packages (right side).

Reasons:
1. Show useful content. This lowers the barrier for new users to understand the UI and interact with it.
2. Most probably users are interested in the latest history entry. Save those users time.

**Comment by timlau** [comment]
I will look at this

**Comment by genodeftest** [comment]
Perfect! Thanks!
