### ISSUE TITLE
Plural forms for strings

### ISSUE THREAD

**Issue by prescott66** [timlau/yumex-dnf#68]
Please make plural forms for these strings:

#: ../src/yumex/dnf_backend.py:237
#, python-format
msgid "Downloading %d files (%sb)..."

#: ../dbus/dbus_status.py:572
#, python-format
msgid "%s available updates"

#: ../dbus/dbus_status.py:280
#, python-format
msgid "Yum Extender: %s updates available"

**Comment by timlau** [comment]
Thanks for reporting

**Comment by timlau** [comment]
These strings are no longer used in current development version, so I will close this issue
