### ISSUE TITLE
[RFE] [User Experience] show number of packages besides expandable label

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#69]
Steps to reproduce:
1. go to history view
2. select a history entry
3. watch the right side

What I would like to happen:
Display the number of packages besides "Erased packages", "Installed packages", "Updated packages", …

This affects:
* history view: package list
* pending actions view: package list
* "Package actions to perform" dialog after pressing the "Apply pending changes" button

**Comment by timlau** [comment]
Sound like a good idea
