### ISSUE TITLE
The margins between the header buttons are inconsistent

### ISSUE THREAD

**Issue by gitjod** [timlau/yumex-dnf#70]
The margin-end and the margin-right values for "GTKMenuButton - header_filters" need to be a value of 6 and not 0 in order for the the margins between the all the header buttons to look consistent

**Comment by timlau** [comment]
Thanks for reporting, I will look into this

**Comment by timlau** [comment]
![image](https://cloud.githubusercontent.com/assets/283985/10941108/31c3d6c4-830a-11e5-9068-eb599af10ab0.png)

It is on purpose that the 2 search related buttons are grouped together

**Comment by gitjod** [comment]
I thought perhaps that might be the case. I think a nicer implementation would be using a GtkToggleButton instead of a GtkSearchEntry with the filters & search options exposed using a GtkArrow appearing in GtkTreeView. Probably best explained using a screenshot of the layout in Gnome-Music.

![image](https://cloud.githubusercontent.com/assets/12417441/10949642/f39a3eca-832b-11e5-96ac-915658d71b21.png)

**Comment by timlau** [comment]
Agree, the UI need some work to be more logic for the user

See discussio in #54 

I will take a look at google music, looks like a good way to do it

**Comment by gitjod** [comment]
Thanks Tim,  I will close this issue as you have now opened #74
