### ISSUE TITLE
yumex-dnf fails when there are new GPG keys for a repo

### ISSUE THREAD

**Issue by pablaasmo** [timlau/yumex-dnf#71]
When CLI version of dnf encounters a new GPG key for a repo it offers to import it.
yumex-dnf fails with an error message.
It should have popped up a message window and ask for permission to import the new key.

example from CLI dnf:

>    warning: /var/cache/dnf/rpmfusion-nonfree-updates-031b4488fbcdfcb3/packages/rpmfusion-nonfree-release-23-0.1.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 5ca6c469: NOKEY
>    Importing GPG key 0x5CA6C469:
>    Userid     : "RPM Fusion nonfree repository for Fedora (23) <rpmfusion-buildsys@lists.rpmfusion.org>"
>     Fingerprint: 15B9 D223 C819 BF69 86A6 F203 D26D EA72 5CA6 C469
>     From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-23
>    Is this ok [y/N]: y

**Comment by pablaasmo** [comment]
![yumex-dnf_error_importing_keys](https://cloud.githubusercontent.com/assets/1215134/10915141/af9f4fac-8255-11e5-9bf7-79383ea623f0.png)

This picture shows error message when there are new keys.

**Comment by timlau** [comment]
I will look into this, this used to work, so something must have broken it.
