### ISSUE TITLE
obsolete packages forcing yumex-dnf to close!

### ISSUE THREAD

**Issue by fduraibi** [timlau/yumex-dnf#75]
Two ownCloud packages always show up in the main list with the updates, their color is blue which is for obsolete packages, however, they are not, see picture.

![yumex-dnf](https://cloud.githubusercontent.com/assets/432460/11066894/05582abc-8798-11e5-9474-f88eb4da5338.png)

I tried to clear the cache, refresh, reinstall, but I couldn't get rid of them.
* I use the 64bit version, but the first item is the i686 which is not installed!
* The 64bit which is installed is the latest (see the rpm output)

They have been showing their for a very long time, even when I get updates for owncloud client.

Here is what happens when I try to "update" them (it happens every time):

* Trying to update the i686 package will fail with this message:

![yumex-dnf1](https://cloud.githubusercontent.com/assets/432460/11067265/c70f23ee-8799-11e5-83be-a47ac67c3ef5.png)

After this failure if I go back to the "Packages" page I get this error message and the application will close:
![yumex-dnf2](https://cloud.githubusercontent.com/assets/432460/11067327/06ead10c-879a-11e5-88a1-8e460b736409.png)

Here is the debug output:
```
$ yumex-dnf -d
10:50:37: cmdline : Namespace(debug=True, exit=False, icononly=False, install=None, minimized=False, remove=None, updateall=False, yes=False) 
10:50:37: dk.yumex.StatusIcon daemon loaded - version :  412
10:50:37: do_activate

(yumex-dnf:10415): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
10:50:38: looking for /home/fad/.themes/oxygen-gtk/apps/yumex.css
10:50:38: looking for /usr/share/themes/oxygen-gtk/apps/yumex.css
10:50:38: Lock the DNF root daemon
10:50:38: get_packages took 0.11 sec
10:50:38: get_packages took 0.01 sec
10:50:38: populate took 0.00 sec
10:50:46: adding: obsolete owncloud-client,0,2.0.2,5.2,i686,isv_ownCloud_desktop
10:50:46: result: False: ['package owncloud-client-2.0.2-5.2.i686 requires owncloud-client-l10n, but none of the providers can be installed']
10:51:00: Unlock the DNF root daemon
10:51:05: EXCEPTION : g-io-error-quark: GDBus.Error:org.baseurl.DnfSystem.LockedError: dnf is locked by another application (36) 
10:51:05: err:  [LockedError] - msg: dnf is locked by another application (36)

(yumex-dnf:10415): Gtk-CRITICAL **: gtk_main_quit: assertion 'main_loops != NULL' failed
```

* Updating the 64bit fails in a similar way but with a different error message and will also force a close of the application:

![yumex-dnf3](https://cloud.githubusercontent.com/assets/432460/11067405/557895b6-879a-11e5-8d66-fe173a915396.png)

![yumex-dnf4](https://cloud.githubusercontent.com/assets/432460/11067407/585c6b4a-879a-11e5-90e2-81959f1127d4.png)

```
$ yumex-dnf -d
10:53:11: cmdline : Namespace(debug=True, exit=False, icononly=False, install=None, minimized=False, remove=None, updateall=False, yes=False) 
10:53:11: dk.yumex.StatusIcon daemon loaded - version :  412
10:53:11: do_activate

(yumex-dnf:10477): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
10:53:11: looking for /home/fad/.themes/oxygen-gtk/apps/yumex.css
10:53:11: looking for /usr/share/themes/oxygen-gtk/apps/yumex.css
10:53:11: Lock the DNF root daemon
10:53:11: get_packages took 0.10 sec
10:53:11: get_packages took 0.00 sec
10:53:11: populate took 0.01 sec
10:53:13: adding: obsolete owncloud-client,0,2.0.2,5.2,x86_64,@System
10:53:14: result: False: []
10:53:45: Unlock the DNF root daemon
10:53:48: EXCEPTION : g-io-error-quark: GDBus.Error:org.baseurl.DnfSystem.LockedError: dnf is locked by another application (36) 
10:53:48: err:  [LockedError] - msg: dnf is locked by another application (36)

(yumex-dnf:10477): Gtk-CRITICAL **: gtk_main_quit: assertion 'main_loops != NULL' failed
```

OS: Fedora 22 64bit with KDE Plasma 5
ownCloud repo source: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Fedora_22/

**Comment by timlau** [comment]
These packages are broken

look like the spec contains
obsoletes: owncloud-client

This mean that the package obsoletes itself

obsoletes without version and args is a very bad thing.

This is how it should be done.
https://fedoraproject.org/wiki/Packaging:Guidelines#Renaming.2FReplacing_Existing_Packages

$ sudo dnf list obsoletes
Last metadata expiration check performed 0:11:05 ago on Fri Nov 27 15:34:46 2015.
Obsoleting Packages
owncloud-client.i686                                      2.0.2-9.2                                 isv_ownCloud_desktop
    owncloud-client.x86_64                                2.0.2-9.2                                 @@commandline       
owncloud-client.x86_64                                    2.0.2-9.2                                 @@commandline       
    owncloud-client.x86_64                                2.0.2-9.2                                 @@commandline       
owncloud-client.x86_64                                    2.0.2-9.2                                 isv_ownCloud_desktop
    owncloud-client.x86_64                                2.0.2-9.2                                 @@commandline       
$ rpm -q owncloud-client.x86_64 --obsoletes

libocsync-devel
libocsync-devel-doc
libocsync-doc
libocsync-plugin-owncloud
libocsync0
libowncloudqt5sync-devel
libowncloudqt5sync0
owncloud-client
owncloud-client-qt5
owncloud-client-qt5-doc
owncloud-client-qt5-l10n

**Comment by timlau** [comment]
There is not much i can do in yumex to handle packages there is broken in this way

**Comment by timlau** [comment]
You should properly use Fedora's own packages
https://fedoraproject.org/wiki/OwnCloud

They even warns against the packages from Open Build Services
