### ISSUE TITLE
[wayland] GtkStatusIcon is broken

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#78]
Currently when starting yumex-dnf on a Gnome+Wayland session (choose option from gdm), no status icon will be displayed. If yumex-dnf is configured to show a status icon, closing yumex will not end the yumex-dnf process. Users always get a "Yum Extender is already running" dialog. User interaction with the status icon won't work either.

**Comment by timlau** [comment]
I not sure spend time on fixing this.
I have replaced it with a much simpler standalone yumex-dnf-updatechecker script without a
Gtk.StatusIcon and not a DBus service.

See issue : #79 for details

**Comment by genodeftest** [comment]
Ok, I didn't see that. Closing in favor of #79. Thank you!
