### ISSUE TITLE
4.1.5 rawhide issue.  

### ISSUE THREAD

**Issue by eddy02** [timlau/yumex-dnf#81]
Version 4.1.4 is ok.
But version 4.5.1 hangs :

/usr/lib/python3.5/site-packages/yumex/__init__.py:69: Warning: invalid cast from 'GtkBox' to 'GtkWindow'
  self.ui.add_from_file(const.DATA_DIR + '/yumex.ui')

(yumex-dnf:5614): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

(yumex-dnf:5614): Gtk-WARNING **: State 0 for YumexPackageView 0x55c7e2a74c00 doesn't match state 128 set via gtk_style_context_set_state ()
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/yumex/__init__.py", line 1329, in do_command_line
    self.do_activate()
  File "/usr/lib/python3.5/site-packages/yumex/__init__.py", line 1232, in do_activate
    self.win = YumexWindow(self, self.status)
  File "/usr/lib/python3.5/site-packages/yumex/__init__.py", line 401, in __init__
    CONFIG.conf.color_normal = color_to_hex(color_normal)
  File "/usr/lib/python3.5/site-packages/yumex/misc.py", line 118, in color_to_hex
    return rgb_to_hex(color.red, color.green, color.blue)
  File "/usr/lib/python3.5/site-packages/yumex/misc.py", line 114, in rgb_to_hex
    return "#%02X%02X%02X" % (r, g, b)
TypeError: %X format: an integer is required, not float

**Comment by timlau** [comment]
Think you ar talking about 4.1.5, not 4.5.1 ;-)

What version of gtk is installed 
It could be related to these changes in gtk.
https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/

**Comment by eddy02** [comment]
Sorry.  
yumex-dnf 4.1.5,  version with gtk-3.19.3 

I'll try  to downgrade gtk for testing.
Thanks

**Comment by timlau** [comment]
@eddy02 does 4.1.4 work for you in current Rawhide ?, many others have problems because dnfdaemon will not load.
https://bugzilla.redhat.com/show_bug.cgi?id=1280181

**Comment by timlau** [comment]
This could also be a change in Python 3.5

Try running this command and see if you get an error
python3 -c "print('%02X' % 255.0)"

**Comment by timlau** [comment]
OK, I have fixed it in 4.1.x & 4.2.x
