### ISSUE TITLE
Search for updates within GUI

### ISSUE THREAD

**Issue by droidmonkey** [timlau/yumex-dnf#84]
There is no button (or obvious button) to initiate a search for updates from within the gui. You must right click the status bar icon to start a search for updates or completely close the gui and statusbar icon and reopen it again fresh.

This would be a nice addition to the far left drop down menu.

**Comment by timlau** [comment]
@droidmonkey have you tried the latest development releases
https://copr.fedoraproject.org/coprs/timlau/yumex-dnf/

The status icon has been replaced by a update checker script, there will give you a notification is new updates is found, so there i not need to keep the yumex-dnf running.

But I still can see a valid use case for wanting to do a forced recheck of the metadata for the gui.

like running dnf update --force.

**Comment by droidmonkey** [comment]
The new GUI is top notch, just updated to the dev release.

Perhaps in the "hamburger menu" on the right there can be a "Force Repo Refresh" selection. That will handle it quite nicely.

**Comment by droidmonkey** [comment]
This menu entry worked when I tried it today. Great job!
