### ISSUE TITLE
no icon in system tray

### ISSUE THREAD

**Issue by krkapes** [timlau/yumex-dnf#86]
hi, this program is ok, but the icon is missing...and the search 
should be more intuitive...but, you have my full suport about this, and a have add this repo to my fedora to suport you :) 
![no_icon](https://cloud.githubusercontent.com/assets/16269816/11763261/c5e12106-a103-11e5-8c03-b051762ca05d.png)

**Comment by timlau** [comment]
What version of yumex-dnf are you talking about ?
