### ISSUE TITLE
Yumex-Dnf Status Bar Text Colour

### ISSUE THREAD

**Issue by LilZebra** [timlau/yumex-dnf#87]
I've begun using Yumex-DNF in the past while. I like it because the program updates list font size is larger than in Yumex.

One thing that should be fixed is the font colour of the status bar "Downloading..." "Applying changes..." part of the program.

Perhaps it's just my setup, but the status bar text is in medium grey on a black background. This is very difficult to see, without having to go up close to my monitor screen.

**Comment by LilZebra** [comment]
Also, how  can I upload a screenshot of this issue? I tried on FedoraForum, but it only allows up to 97 K images?

**Comment by timlau** [comment]
You can just cut & paste the picture here or drag & drop it into a comment

**Comment by LilZebra** [comment]
James A Jaworski
LilZebra Publishing Ltd.
22 St. Andrew Rd., St. Vital, MB, R2M 3H5
e. jimj_wpg@yahoo.ca
c. 204.890.4716

**Comment by LilZebra** [comment]
file:///home/lilzebra/Pictures/Yum%20Extender%20-%20Powered%20by%20DNF_768.png

**Comment by LilZebra** [comment]
I used Nautilus to drag and drop the .png image, but all I see here is the Local URL.

**Comment by timlau** [comment]
@LilZebra Just click on the  **selecting them** link in the button of the comment box

**Comment by LilZebra** [comment]
![yum extender - powered by dnf_768](https://cloud.githubusercontent.com/assets/13359774/11811775/2efa0aa4-a2fd-11e5-9663-9099ee533e60.png)
