### ISSUE TITLE
Conflict window does not resize to screen

### ISSUE THREAD

**Issue by mpsOxygen** [timlau/yumex-dnf#90]
I tried updating gtk2 and gtk2-devel packages on fedora and it gave an error while resolving dependecies. The packages conflict with some other packages and it gave me a huge list of problems that where beyond the top and bottom of my screen. I couln't click it, couldn't move it and it broke the alignment of windows when I press the super key.

**Comment by genodeftest** [comment]
I ran into this one too.

Cause for this issue:
`src/yumex/gui/dialogs.py:260 in show_information`: if `msg` is huge, it will create a GtkMessageDialog that is taller and/or wider than the screen. This should not happen.

**Comment by timlau** [comment]
Agree, we need a custom dialog with scrollbars to show error messages
