### ISSUE TITLE
Feature suggestion - Improved Search

### ISSUE THREAD

**Issue by careca1970** [timlau/yumex-dnf#91]
First of all. Thanks for the good work!
I can remember, I was able to get better results for my searches under old YUMEX...

Why YUMEX-DNF does not search for keywords from other fields than just the package-name?
Why not include other fields as Package-descriptions, Summary, etc.?

Maybe even include regular expressions additionally to wildcards...

**Comment by timlau** [comment]
Just select fields in search options and it will search in the fields you select.
there is 3 search types for performance reasons and the dnf API for searching is diffent than the yum API was, so I have made 2 kind of package name search and one for user defined fields.
try the version of yumex in the Fedora COPR repo (timlau\yumex-dnf) it is more intuitive (I Hope)

**Comment by careca1970** [comment]
Problem of modern UI design is that the user must TRY clicking everywhere to find out WHAT is possible, and maybe, thou NOT...
Meanwhile I had DISCOVERED how to use search here...
Many thanks!
