### ISSUE TITLE
add support for verbose output

### ISSUE THREAD

**Issue by pouar** [timlau/yumex-dnf#96]
One feature I really miss from the old yumex was being able to see the output in the window. Any chance there can be an option in yumex-dnf for this?

**Comment by rlengland** [comment]
+1 I miss this as well.

**Comment by timlau** [comment]
you cant not get the same verbose information from dnf API as from the yum API.

there is a yumex-dnf -d, but is more for debuging problem in yumex-dnf, than to give you the information you want.
