### ISSUE TITLE
There is no way to remove package, which has an update

### ISSUE THREAD

**Issue by ghost** [timlau/yumex-dnf#97]
If some package have an update in repository, there is no way to select it for removing. No keyboard shortcuts, no context menu... The only way to remove such package using yumex-dnf, is to update it first, and only when - remove it.

That's weird.

**Comment by ghost** [comment]
I am a bit too hurried to report a bug. Because I found the way to remove package, which has an update. This is to uncheck the "Newest Only" tick.

So, this must refer to issue #53.

**Comment by timlau** [comment]
Yes, exactly :-D
